spring.application.name=Back
spring.data.mongodb.uri=mongodb://localhost:27017/furniture_marketplace
spring.data.mongodb.auto-index-creation=true
server.port=8080

jwt.secret=mebliHubSuperSecretKeyForJwtTokenSigningThatIsLongEnoughForHS256Algorithm2024
jwt.expiration=86400000

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.data.mongodb.repository.query=DEBUG
logging.level.org.mongodb.driver.protocol.command=DEBUG
